// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestReach.Exam.Data.Contexts;

namespace TestReach.Exam.Data.Migrations
{
    [DbContext(typeof(ExamContext))]
    [Migration("20211025033549_AddInitialExamData")]
    partial class AddInitialExamData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestReach.Exam.Domain.Entities.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChosenOption")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<Guid>("ExamAttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExamAttemptId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("TestReach.Exam.Domain.Entities.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("TestReach.Exam.Domain.Entities.Exam", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exams");

                    b.HasData(
                        new
                        {
                            Id = "EX202001",
                            CreationDate = new DateTime(2021, 10, 25, 0, 35, 49, 683, DateTimeKind.Local).AddTicks(1948),
                            Name = "Exam 1"
                        },
                        new
                        {
                            Id = "EX202002",
                            CreationDate = new DateTime(2021, 10, 25, 0, 35, 49, 683, DateTimeKind.Local).AddTicks(7712),
                            Name = "Exam 2"
                        },
                        new
                        {
                            Id = "EX202003",
                            CreationDate = new DateTime(2021, 10, 25, 0, 35, 49, 683, DateTimeKind.Local).AddTicks(7722),
                            Name = "Exam 3"
                        },
                        new
                        {
                            Id = "EX202004",
                            CreationDate = new DateTime(2021, 10, 25, 0, 35, 49, 683, DateTimeKind.Local).AddTicks(7724),
                            Name = "Exam 4"
                        });
                });

            modelBuilder.Entity("TestReach.Exam.Domain.Entities.ExamAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AttemptDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExamId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("ExamId");

                    b.ToTable("ExamAttempts");
                });

            modelBuilder.Entity("TestReach.Exam.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("ExamId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("04303027-7a5e-4ff1-a792-2ad43070ce93"),
                            CorrectAnswer = "A",
                            ExamId = "EX202001",
                            QuestionNumber = 1
                        },
                        new
                        {
                            Id = new Guid("5f1e8b37-4699-4cea-b1c8-173da1dfb6ee"),
                            CorrectAnswer = "C",
                            ExamId = "EX202001",
                            QuestionNumber = 2
                        },
                        new
                        {
                            Id = new Guid("5719bf76-6bd4-40db-b6b1-cc257bdb1256"),
                            CorrectAnswer = "C",
                            ExamId = "EX202001",
                            QuestionNumber = 3
                        },
                        new
                        {
                            Id = new Guid("bb087f75-93e3-4de8-a50b-b79b63ef224a"),
                            CorrectAnswer = "A",
                            ExamId = "EX202001",
                            QuestionNumber = 4
                        },
                        new
                        {
                            Id = new Guid("3a12e8ff-4bb4-4464-b987-a8640ac066db"),
                            CorrectAnswer = "B",
                            ExamId = "EX202001",
                            QuestionNumber = 5
                        },
                        new
                        {
                            Id = new Guid("b20a7903-7c08-444b-b1d3-58abb454c6f0"),
                            CorrectAnswer = "B",
                            ExamId = "EX202001",
                            QuestionNumber = 6
                        },
                        new
                        {
                            Id = new Guid("d32e8a1b-17ac-46d4-ac5e-306374f752af"),
                            CorrectAnswer = "C",
                            ExamId = "EX202001",
                            QuestionNumber = 7
                        },
                        new
                        {
                            Id = new Guid("4a5f8d24-4fc1-4e33-9e3d-6b8e52f6c345"),
                            CorrectAnswer = "A",
                            ExamId = "EX202001",
                            QuestionNumber = 8
                        },
                        new
                        {
                            Id = new Guid("bd2c9dce-7c1a-430e-818a-141dd8fcfc3a"),
                            CorrectAnswer = "D",
                            ExamId = "EX202001",
                            QuestionNumber = 9
                        },
                        new
                        {
                            Id = new Guid("e7ece826-5e40-4175-869d-c85a70ad866f"),
                            CorrectAnswer = "A",
                            ExamId = "EX202001",
                            QuestionNumber = 10
                        },
                        new
                        {
                            Id = new Guid("af6d75d3-e287-4f5b-9292-e40fd3847933"),
                            CorrectAnswer = "B",
                            ExamId = "EX202002",
                            QuestionNumber = 1
                        },
                        new
                        {
                            Id = new Guid("b47e9a9a-10b2-41e3-9185-1a7e740ef64e"),
                            CorrectAnswer = "D",
                            ExamId = "EX202002",
                            QuestionNumber = 2
                        },
                        new
                        {
                            Id = new Guid("e1b10568-cc3b-4a1f-8bf7-ad5477fbe422"),
                            CorrectAnswer = "C",
                            ExamId = "EX202002",
                            QuestionNumber = 3
                        },
                        new
                        {
                            Id = new Guid("1b702dc4-fc22-4379-9628-4a2a49adca07"),
                            CorrectAnswer = "C",
                            ExamId = "EX202002",
                            QuestionNumber = 4
                        },
                        new
                        {
                            Id = new Guid("6c68197a-13de-4231-a0ab-25e3bc2645eb"),
                            CorrectAnswer = "A",
                            ExamId = "EX202002",
                            QuestionNumber = 5
                        },
                        new
                        {
                            Id = new Guid("71b11817-4287-4f88-b3ce-1490c59c3457"),
                            CorrectAnswer = "D",
                            ExamId = "EX202002",
                            QuestionNumber = 6
                        },
                        new
                        {
                            Id = new Guid("3ce99c72-9b75-472f-839d-be773c526284"),
                            CorrectAnswer = "E",
                            ExamId = "EX202002",
                            QuestionNumber = 7
                        },
                        new
                        {
                            Id = new Guid("24b175d4-296b-41ba-8f56-553c4706fc3c"),
                            CorrectAnswer = "E",
                            ExamId = "EX202002",
                            QuestionNumber = 8
                        },
                        new
                        {
                            Id = new Guid("d49573ed-c32c-4fea-ad99-e737c86204d0"),
                            CorrectAnswer = "C",
                            ExamId = "EX202002",
                            QuestionNumber = 9
                        },
                        new
                        {
                            Id = new Guid("db8f1e58-7d66-4d82-a4a0-7ba06e0d5407"),
                            CorrectAnswer = "A",
                            ExamId = "EX202002",
                            QuestionNumber = 10
                        },
                        new
                        {
                            Id = new Guid("3006a35f-03b1-4ffb-9406-73eac9b9f509"),
                            CorrectAnswer = "E",
                            ExamId = "EX202002",
                            QuestionNumber = 11
                        },
                        new
                        {
                            Id = new Guid("ad5b5c85-c1ef-439e-b375-a976e093a424"),
                            CorrectAnswer = "C",
                            ExamId = "EX202002",
                            QuestionNumber = 12
                        },
                        new
                        {
                            Id = new Guid("39b89e8d-ed1d-4722-9264-22658df29fa4"),
                            CorrectAnswer = "D",
                            ExamId = "EX202002",
                            QuestionNumber = 13
                        },
                        new
                        {
                            Id = new Guid("ffa55825-3886-4501-a2e1-79d7c28bf206"),
                            CorrectAnswer = "E",
                            ExamId = "EX202002",
                            QuestionNumber = 14
                        },
                        new
                        {
                            Id = new Guid("9000f4bb-15dc-42de-b2fb-fb5b030b24c5"),
                            CorrectAnswer = "A",
                            ExamId = "EX202002",
                            QuestionNumber = 15
                        },
                        new
                        {
                            Id = new Guid("52b0970e-61cd-4a48-a119-1110ae365f6f"),
                            CorrectAnswer = "B",
                            ExamId = "EX202002",
                            QuestionNumber = 16
                        },
                        new
                        {
                            Id = new Guid("ec653cb5-3de4-435f-93eb-0b9bfd93a3f7"),
                            CorrectAnswer = "D",
                            ExamId = "EX202002",
                            QuestionNumber = 17
                        },
                        new
                        {
                            Id = new Guid("ed8cc69e-2825-49fb-b9fd-ddb26b3c3ef4"),
                            CorrectAnswer = "B",
                            ExamId = "EX202003",
                            QuestionNumber = 1
                        },
                        new
                        {
                            Id = new Guid("f220cc33-9c71-4d26-ba27-5801a50405ce"),
                            CorrectAnswer = "C",
                            ExamId = "EX202003",
                            QuestionNumber = 2
                        },
                        new
                        {
                            Id = new Guid("8a5151ea-88ad-42f5-b18f-9faeb4e1d778"),
                            CorrectAnswer = "E",
                            ExamId = "EX202003",
                            QuestionNumber = 3
                        },
                        new
                        {
                            Id = new Guid("1f91591e-0a70-4d46-8a41-53f3f0b953a1"),
                            CorrectAnswer = "E",
                            ExamId = "EX202003",
                            QuestionNumber = 4
                        },
                        new
                        {
                            Id = new Guid("22248d38-3267-4132-b2f6-c7c671504839"),
                            CorrectAnswer = "A",
                            ExamId = "EX202003",
                            QuestionNumber = 5
                        },
                        new
                        {
                            Id = new Guid("a3f12cb7-1844-4b76-b750-542e3ca8fa61"),
                            CorrectAnswer = "C",
                            ExamId = "EX202003",
                            QuestionNumber = 6
                        },
                        new
                        {
                            Id = new Guid("ec6d68f3-5d35-478a-87b3-fc5f667b27f6"),
                            CorrectAnswer = "D",
                            ExamId = "EX202003",
                            QuestionNumber = 7
                        },
                        new
                        {
                            Id = new Guid("257fbd47-3033-419c-b4dc-7f7387d4afd8"),
                            CorrectAnswer = "E",
                            ExamId = "EX202003",
                            QuestionNumber = 8
                        },
                        new
                        {
                            Id = new Guid("d4a1f573-d278-45c5-8811-97b352b294ed"),
                            CorrectAnswer = "A",
                            ExamId = "EX202003",
                            QuestionNumber = 9
                        },
                        new
                        {
                            Id = new Guid("09727a0f-2d4b-435c-ba17-665878c1c419"),
                            CorrectAnswer = "A",
                            ExamId = "EX202003",
                            QuestionNumber = 10
                        },
                        new
                        {
                            Id = new Guid("aab3cee1-71af-4598-9e11-ef7f19caeadd"),
                            CorrectAnswer = "E",
                            ExamId = "EX202003",
                            QuestionNumber = 11
                        },
                        new
                        {
                            Id = new Guid("faedf7e4-5c5b-4205-b503-7eed61d88cc0"),
                            CorrectAnswer = "C",
                            ExamId = "EX202003",
                            QuestionNumber = 12
                        },
                        new
                        {
                            Id = new Guid("18c1ba39-faa4-49a4-98e6-32c1afe1b112"),
                            CorrectAnswer = "B",
                            ExamId = "EX202003",
                            QuestionNumber = 13
                        },
                        new
                        {
                            Id = new Guid("e659c85d-9472-41a7-a98f-b505155ba3a8"),
                            CorrectAnswer = "A",
                            ExamId = "EX202003",
                            QuestionNumber = 14
                        },
                        new
                        {
                            Id = new Guid("9987532c-0df2-4a25-9755-eee05740ed13"),
                            CorrectAnswer = "B",
                            ExamId = "EX202003",
                            QuestionNumber = 15
                        },
                        new
                        {
                            Id = new Guid("3d39dd09-f6e5-4d79-a7f8-e04cf52b3d94"),
                            CorrectAnswer = "C",
                            ExamId = "EX202003",
                            QuestionNumber = 16
                        },
                        new
                        {
                            Id = new Guid("8abd0874-567a-4027-8e23-e8d27f7f8c15"),
                            CorrectAnswer = "A",
                            ExamId = "EX202003",
                            QuestionNumber = 17
                        },
                        new
                        {
                            Id = new Guid("54146f0e-db7e-4d4e-84aa-5b4f2bf1c425"),
                            CorrectAnswer = "B",
                            ExamId = "EX202003",
                            QuestionNumber = 18
                        },
                        new
                        {
                            Id = new Guid("b493caa7-c4da-45bc-903c-812839af7678"),
                            CorrectAnswer = "B",
                            ExamId = "EX202003",
                            QuestionNumber = 19
                        },
                        new
                        {
                            Id = new Guid("768fd656-3496-4ba0-8924-e7839a9f67ce"),
                            CorrectAnswer = "D",
                            ExamId = "EX202003",
                            QuestionNumber = 20
                        },
                        new
                        {
                            Id = new Guid("879dacbf-ff69-4d3a-8769-2e341087f2bb"),
                            CorrectAnswer = "E",
                            ExamId = "EX202004",
                            QuestionNumber = 1
                        },
                        new
                        {
                            Id = new Guid("9b307e7b-7fb4-4e8c-aca7-1d9e6ed5f2d2"),
                            CorrectAnswer = "A",
                            ExamId = "EX202004",
                            QuestionNumber = 2
                        },
                        new
                        {
                            Id = new Guid("313bd5af-0ca5-45ae-9ec5-9b34d42c2fa4"),
                            CorrectAnswer = "C",
                            ExamId = "EX202004",
                            QuestionNumber = 3
                        },
                        new
                        {
                            Id = new Guid("ebda3531-5261-48ea-a8bb-46c2166e0e96"),
                            CorrectAnswer = "D",
                            ExamId = "EX202004",
                            QuestionNumber = 4
                        },
                        new
                        {
                            Id = new Guid("c976e399-c219-445c-9bcf-7fbee1b8f53f"),
                            CorrectAnswer = "E",
                            ExamId = "EX202004",
                            QuestionNumber = 5
                        },
                        new
                        {
                            Id = new Guid("ee1330c0-db69-4eb3-ab5f-87be43636018"),
                            CorrectAnswer = "A",
                            ExamId = "EX202004",
                            QuestionNumber = 6
                        },
                        new
                        {
                            Id = new Guid("b725149d-5635-4ffc-b466-efe4400408c4"),
                            CorrectAnswer = "A",
                            ExamId = "EX202004",
                            QuestionNumber = 7
                        },
                        new
                        {
                            Id = new Guid("d1acadc7-2085-433c-8ed7-a58893d26e47"),
                            CorrectAnswer = "E",
                            ExamId = "EX202004",
                            QuestionNumber = 8
                        },
                        new
                        {
                            Id = new Guid("6e486c0c-2b55-45b7-b73e-663fdac42176"),
                            CorrectAnswer = "C",
                            ExamId = "EX202004",
                            QuestionNumber = 9
                        },
                        new
                        {
                            Id = new Guid("e93dc31b-c9c0-4076-a263-9dfaccdc6c5d"),
                            CorrectAnswer = "B",
                            ExamId = "EX202004",
                            QuestionNumber = 10
                        },
                        new
                        {
                            Id = new Guid("e16d0d52-0f76-404a-8823-fe6dcf96d272"),
                            CorrectAnswer = "A",
                            ExamId = "EX202004",
                            QuestionNumber = 11
                        },
                        new
                        {
                            Id = new Guid("47e447d4-8cc8-4d52-960a-cb8da8474c9e"),
                            CorrectAnswer = "B",
                            ExamId = "EX202004",
                            QuestionNumber = 12
                        });
                });

            modelBuilder.Entity("TestReach.Exam.Domain.Entities.Answer", b =>
                {
                    b.HasOne("TestReach.Exam.Domain.Entities.ExamAttempt", "ExamAttempt")
                        .WithMany("Answers")
                        .HasForeignKey("ExamAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamAttempt");
                });

            modelBuilder.Entity("TestReach.Exam.Domain.Entities.ExamAttempt", b =>
                {
                    b.HasOne("TestReach.Exam.Domain.Entities.Candidate", "Candidate")
                        .WithMany("ExamAttempts")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestReach.Exam.Domain.Entities.Exam", "Exam")
                        .WithMany("ExamAttempts")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("TestReach.Exam.Domain.Entities.Question", b =>
                {
                    b.HasOne("TestReach.Exam.Domain.Entities.Exam", "Exam")
                        .WithMany("Questions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("TestReach.Exam.Domain.Entities.Candidate", b =>
                {
                    b.Navigation("ExamAttempts");
                });

            modelBuilder.Entity("TestReach.Exam.Domain.Entities.Exam", b =>
                {
                    b.Navigation("ExamAttempts");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("TestReach.Exam.Domain.Entities.ExamAttempt", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
